# Generated by Django 4.1.1 on 2022-09-23 19:26

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Zdjęcie')),
                ('title', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Aktualizacja')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorii',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('second_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('company', models.CharField(max_length=100, null=True, verbose_name='Firma')),
                ('street', models.CharField(max_length=100, verbose_name='Ulica')),
                ('city', models.CharField(max_length=100, verbose_name='Miejscowość')),
                ('zip_code', models.CharField(max_length=100, verbose_name='Kod pocztowy')),
                ('phone', models.CharField(max_length=100, verbose_name='Kod pocztowy')),
                ('email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('short_title', models.CharField(max_length=22, null=True, verbose_name='Krótki tytuł')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('price', models.FloatField(default=0, verbose_name='Cena')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='Cena ze zniżką')),
                ('quantity', models.IntegerField(default=0)),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Opis')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Zdjęcie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Czas dodania')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Aktualizacja')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowane')),
                ('views', models.IntegerField(default=0, verbose_name='Liczba wyświetleń')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='core.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Czas zamówienia')),
                ('complete', models.BooleanField(default=False, null=True, verbose_name='Kompletny')),
                ('is_shipped', models.BooleanField(default=False, verbose_name='Wysłane')),
                ('is_shipped_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('canceled', models.BooleanField(default=False, verbose_name='Anulowane')),
                ('canceled_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ManyToManyField(to='core.customer', verbose_name='Klient')),
            ],
            options={
                'verbose_name': 'Zamówienia',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True, verbose_name='Identyfikator')),
                ('company', models.CharField(max_length=50, null=True, verbose_name='Dostawca')),
                ('price', models.FloatField(default=0, verbose_name='Cena')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Czas dostawy')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('second_name', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('shipment', models.CharField(max_length=200, null=True)),
                ('payment_options', models.CharField(max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True, verbose_name='Kwota')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Czas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mainorder', verbose_name='Zamówienia')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Płatności',
            },
        ),
        migrations.CreateModel(
            name='MainOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zamówione artykuły',
            },
        ),
        migrations.AddField(
            model_name='mainorder',
            name='items',
            field=models.ManyToManyField(to='core.mainorderitem', verbose_name='Zamówione artykuły'),
        ),
        migrations.AddField(
            model_name='mainorder',
            name='shipping_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shippingdata', verbose_name='Wysyłka'),
        ),
        migrations.AddField(
            model_name='mainorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
